export const GET_CHAT_USER_LIST = 'GET_CHAT_USER_LIST';
export const CREATE_CHAT = 'CREATE_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const CHAT_LIST = 'CHAT_LIST';
export const UPDATE_ACTIVE_RECEIVER = 'UPDATE_ACTIVE_RECEIVER';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_ACTIVE_MESSAGES = 'UPDATE_ACTIVE_MESSAGES';